const express = require('express')
const cookieParser = require('cookie-parser')
const sessions = require('./lib/sessions')
const bodyParser = require('body-parser')
const router = require('./lib/router')
process.env.HOME = __dirname + '/public/home.html'
module.exports = exports = express()

exports.use(cookieParser())
exports.use(sessions)
exports.use(bodyParser.urlencoded())
exports.engine('html', require('ejs').renderFile)
exports.set('view engine', 'html')
exports.set('views', __dirname + '/views')
exports.use(express.json())
exports.use(express.static('public'))
exports.use('/', router())
exports.use(/\/.*/, router())
