const express = require('express')
const cookieParser = require('cookie-parser')
const sessions = require('./lib/sessions')
const bodyParser = require('body-parser')
const router = require('./lib/router')
const axiosRouter = require('./lib/axios-router')
process.env.HOME = __dirname + '/public/home.html'
module.exports = exports = express()

exports.use(cookieParser())
exports.use(sessions)
exports.use(bodyParser.urlencoded())
exports.use('/api', router())
exports.use(express.json())
exports.use(/\/.+/, axiosRouter())
exports.use(express.static('public'))
